eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-peer1:8761/eureka,http://eureka-peer2:8762/eureka
---
spring:
  profiles: lazy
activities: learn something new, take a break, get a job, copy code from Stack Overflow
server:
  port: 8010
---
spring:
  profiles: crazy
activities: go back to work, create another microservice, refresh the page to get new values, be even more productive
server:
  port: 8011
