eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-peer1:8761/eureka,http://eureka-peer2:8762/eureka
---
spring:
  profiles: lazy
activities: First activity lazy value, Second activity lazy value
server:
  port: 8010
---
spring:
  profiles: crazy
activities: First activity crazy value, Second activity crazy value
server:
  port: 8011
