eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-peer1:8761/eureka,http://eureka-peer2:8762/eureka
---
spring:
  profiles: polite
decisions: Time to, Let's, Perfect moment to, Good time to
server:
  port: 8000
---
spring:
  profiles: rough
decisions: I'm about to, I'd like to, Why not just, Last time to
server:
  port: 8001
