eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-peer1:8761/eureka,http://eureka-peer2:8762/eureka
---
spring:
  profiles: polite
decisions: First decision polite value, Second decision polite value
server:
  port: 8000
---
spring:
  profiles: rough
decisions: First decision rough value, Second decision rough value
server:
  port: 8001
